# Generated by Django 3.1.4 on 2021-01-01 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210101_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='following',
            field=models.ManyToManyField(related_name='users_followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
