# Generated by Django 3.1.4 on 2020-12-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=255)),
                ('active', models.BooleanField()),
                ('date', models.DateTimeField()),
                ('start_bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
