# Generated by Django 3.1.4 on 2020-12-22 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='date',
        ),
    ]
